In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list the files in the input directory

import os
print(os.listdir("../input"))

# Any results you write to the current directory are saved as output.

['Project 1 data.csv']


In [2]:
from keras import layers
from keras.layers import Input,Dense,Activation,ZeroPadding2D,Flatten,Conv2D,MaxPooling2D,AveragePooling2D
from keras.layers import GlobalMaxPooling2D,GlobalAveragePooling2D,BatchNormalization,Dropout
from keras.utils import np_utils,print_summary
from keras.models import Sequential
from keras.callbacks import ModelCheckpoint
import keras.backend as k

Using TensorFlow backend.


In [3]:
data=pd.read_csv("../input/Project 1 data.csv")

In [4]:
data.head()

pixel_0000  pixel_0001    ...      pixel_1023  character
0           0           0    ...               0          1
1           0           0    ...               0          1
2           0           0    ...               0          1
3           0           0    ...               0          1
4           0           0    ...               0          1

[5 rows x 1025 columns]

In [5]:
dataset=np.array(data)

In [6]:
np.random.shuffle(dataset)

In [7]:
x=dataset
y=dataset
x=x[:,0:1024]
y=y[:,1024]

In [8]:
x

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [9]:
y

array([ 3, 33, 19, ..., 22,  1, 28])

In [10]:
y.shape

(72000,)

In [11]:
X_train = x[0:70000,:]

In [12]:
X_train.shape

(70000, 1024)

In [13]:
X_train=X_train/255

In [14]:
Y_train = y[0:70000]

In [15]:
X_test=x[70000:,:]

In [16]:
X_test=X_test/255

In [17]:
Y_test=y[70000:]

In [18]:
Y_test.shape

(2000,)

In [19]:
Y_train=Y_train.T

In [20]:
Y_test=Y_test.T

In [21]:
X_train.shape

(70000, 1024)

In [22]:
Y_train.shape

(70000,)

In [23]:
Y_test.shape

(2000,)

In [24]:
X_test.shape

(2000, 1024)

In [25]:
train_y=np_utils.to_categorical(Y_train)

In [26]:
train_y.shape

(70000, 37)

In [27]:
test_y=np_utils.to_categorical(Y_test)

In [28]:
test_y.shape

(2000, 37)

In [29]:
X_train.shape

(70000, 1024)

In [30]:
train_x=X_train.reshape(70000,32,32,1)

In [31]:
train_x.shape

(70000, 32, 32, 1)

In [32]:
test_x=X_test.reshape(2000,32,32,1)

In [33]:
model=Sequential()

In [34]:
model.add(Conv2D(filters=32,kernel_size=(3,3),input_shape=(32,32,1),activation='relu'))

In [35]:
model.add(MaxPooling2D(pool_size=(2,2),strides=(2,2),padding='same'))

In [36]:
model.add(Conv2D(filters=64,kernel_size=(5,5),activation='relu'))

In [37]:
model.add(MaxPooling2D(pool_size=(2,2),strides=(2,2),padding='same'))

In [38]:
model.add(Flatten())

In [39]:
model.add(Dense(37,activation='softmax'))
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])


In [40]:
model.fit(train_x,train_y,batch_size=300,epochs=10,validation_split=0.1)

Train on 63000 samples, validate on 7000 samples
Epoch 1/10
63000/63000 [==============================] - 8s 125us/step - loss: 1.0803 - acc: 0.7110 - val_loss: 0.4296 - val_acc: 0.8729
Epoch 2/10
63000/63000 [==============================] - 4s 59us/step - loss: 0.2745 - acc: 0.9198 - val_loss: 0.2499 - val_acc: 0.9274
Epoch 3/10
63000/63000 [==============================] - 4s 60us/step - loss: 0.1729 - acc: 0.9487 - val_loss: 0.1856 - val_acc: 0.9457
Epoch 4/10
63000/63000 [==============================] - 4s 60us/step - loss: 0.1248 - acc: 0.9626 - val_loss: 0.1582 - val_acc: 0.9533
Epoch 5/10
63000/63000 [==============================] - 4s 59us/step - loss: 0.0953 - acc: 0.9711 - val_loss: 0.1501 - val_acc: 0.9554
Epoch 6/10
63000/63000 [==============================] - 4s 60us/step - loss: 0.0747 - acc: 0.9776 - val_loss: 0.1466 - val_acc: 0.9583
Epoch 7/10
63000/63000 [==============================] - 4s 63us/step - loss: 0.0606 - acc: 0.9821 - val_loss: 0.1312 - val_acc

In [41]:
pred=model.predict(test_x)

In [42]:
pred=np.argmax(pred,axis=1)

In [43]:
pred

array([24, 11, 20, ..., 22,  1, 28])

In [44]:
from sklearn.metrics import accuracy_score

In [45]:
accuracy_score(Y_test, pred)

0.965

In [46]:
model.save('devnagri.h5')